### ISSUE TITLE
v0.2

### ISSUE THREAD

**Issue by SaFrMo** [breakfast-studio/lunchboxjs#29]
Roadmap for releasing 0.2.0:

- [x] Fix demos:
    - [x] Utility Functions
    - [x] Controls
    - [x] UpdateSource
    - [x] UpdateSourceB
    - [x] Custom Scene
    - [x] Camera Switch
- [x] Update inline documentation (all `// TODO: Document` instances in code)
- [x] Update docs site
    - [x] Document `useX` composables
    - [x] Remove `ensure` documentation
    - [x] Update Lunchbox internal structure
- [x] #32

**Comment by SaFrMo** [comment]
@Korijn Would you be interested in taking the last issue on this list, the cross-platform install? I don't have a PC available to test the updates. No worries if not, thanks either way!

**Comment by Korijn** [comment]
No problem, I'll pick that up!

**Comment by SaFrMo** [comment]
Completed in #31
