### ISSUE TITLE
OrbitControls is breaking the app

### ISSUE THREAD

**Issue by alvarosabu** [breakfast-studio/lunchboxjs#37]
Hi there,

I follow the documentation here https://docs.lunchboxjs.com/components/extend/#extend but I get this error and the app just hangs 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'style')
    at new OrbitControls (OrbitControls.js:30:19)
    at instantiateThreeObject (lunchboxjs.module.js:816:20)
    at createNode (lunchboxjs.module.js:95:21)
    at createElement (lunchboxjs.module.js:1402:16)
    at mountElement (runtime-core.esm-bundler.js:5172:25)
    at processElement (runtime-core.esm-bundler.js:5162:13)
    at patch (runtime-core.esm-bundler.js:5082:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5622:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
    at instance.update (runtime-core.esm-bundler.js:5729:56)
```

Any idea? 

## Reproduction
https://stackblitz.com/edit/vitejs-vite-ffatgw?file=src%2FApp.vue,src%2Fmain.ts

**Comment by SaFrMo** [comment]
Hey! Thanks for the question, that example I wrote in the docs is a bit confusingly worded so I'll mark it for updating.

The error you're seeing is a ThreeJS error - you need to provide the `camera` and `renderer.domElement` arguments to the OrbitControls component. See [this example](https://github.com/breakfast-studio/lunchboxjs/blob/main/extras/OrbitControlsWrapper.vue) for a working OrbitControls component; if you add that component to your project, just make sure you change this line:

```ts
import { onBeforeRender, Lunch, useCamera, useRenderer } from '../src'
```

to:

```ts
import { onBeforeRender, Lunch, useCamera, useRenderer } from 'lunchboxjs'
```

Let me know if that doesn't work and I'll take another look!

**Comment by alvarosabu** [comment]
Hey there @SaFrMo thanks for answering so quickly, I try to set up the example that you provide. 
Now the scene is renderer but the orbit controls don't work yet.

Make sense to pass the args, but maybe we could abstract it in form of a helper to avoid updating the controls and having to wait for the renderer and camera to load, using refs, etc, 

An experience similar to how [r3f drie](https://github.com/pmndrs/drei) does (check this [stackblitz](https://stackblitz.com/edit/vitejs-vite-4qv7ap?file=src%2Fcomponents%2FExperience.tsx)), where you only pass `<OrbitControls  />`, the current implementation might be too many steps for users. Wdyt?


I updated https://stackblitz.com/edit/vitejs-vite-ffatgw?file=src/App.vue with the code provided if you want to take a look

**Comment by SaFrMo** [comment]
Got it, thanks! Dug in a little more and fixed the issue in [this stackblitz](https://stackblitz.com/edit/vitejs-vite-2sjsf4?file=src/App.vue) - I moved the camera back instead of moving the cube forward, and the camera not being at position (0,0,0) seemed to fix the issue. 

The good thing is that that seems like a Three issue rather than a Lunchbox one, but you're definitely right that that's a few too many steps to handle a very common use case - started #38 to plan for a fix to that.

Closing this issue with the fix provided, feel free to reopen if needed though!
