### ISSUE TITLE
Migrate to a monorepo structure

### ISSUE THREAD

**Issue by SaFrMo** [breakfast-studio/lunchboxjs#38]
Migrate to a structure that allows developing Lunchbox core alongside useful components (r3f/drei style). Example `packages/` directory could be:

* lunchboxjs (core)
* components
  * extras (all-in-one export of orbit-controls, postprocessing, and any other components that might come up)
  * orbit-controls (OrbitControls implementation, see #37)
  * postprocessing (custom render function implementation)
* composables
* demos

**Comment by alvarosabu** [comment]
Sounds amazing.

Pnpm workspaces works really well with changeset workflow. 

Based on conventional commits you run chageset command on root, select which packages should generate a new version (major, minor, patch) and with a github action it vreates a release PR with the publishing.

**Comment by SaFrMo** [comment]
@alvarosabu This is looking like a `plugins` route might be more useful than `components` - see [here](https://github.com/breakfast-studio/lunchboxjs/tree/38-migrate-to-a-monorepo-structure/packages/plugins) for what I mean, with the `src/orbit` as an example. Just wanted to give you a heads-up - will note when we're closer to a PR!

**Comment by SaFrMo** [comment]
@alvarosabu I'm loving the pnpm workspace workflow, thanks for suggesting! Can you take a look at [this branch](https://github.com/breakfast-studio/lunchboxjs/tree/38-migrate-to-a-monorepo-structure) when you have a moment and see if it matches what you'd expect from a pnpm monorepo? Specifically:

* `npm run dev` should run `dev` on all three packages.
* localhost:5173 should serve `demos`, click on "Loader" to see the orbit controls imported from the plugins workspace. 
* localhost:5174 should serve the plugins workspace, where you can see the orbit controls and gltf loader in place.
* `npm run build` should build main LunchboxJS library.

I stopped moving demos with just the Loader so I don't duplicate your work with histoire - just wanted to make sure this is the kind of thing you were expecting. Let me know any thoughts! 

My planned next steps are to (a) move `demos` back into the lunchboxjs workspace, (b) merge this PR to main, and (c) hand off to you to work on moving those to histoire. Happy to adjust or talk that through if it helps at all. Thanks!

**Comment by SaFrMo** [comment]
All set with moving `demos` back into the lunchboxjs workspace - I'm going to merge this to main so it can be the definitive version for histoire demos per #39 , but please do let me know if there's any unexpected structure here and we can make a new issue to address!
