### ISSUE TITLE
Use histoire for demos

### ISSUE THREAD

**Issue by alvarosabu** [breakfast-studio/lunchboxjs#39]
Hi there, another fresh idea, we could use https://histoire.dev/ for the examples instead of a local vite server.  ;) 

R3F does the same with Storybook. I think is a brilliant idea because It comes with a nice interface to embed and organize all the examples and can be deployed as a static page.

If you are interested I can create the PR

**Comment by SaFrMo** [comment]
Good idea, love this thought! Does it still support local-only dev? That's my main concern as far as demos - I want it to be as easy to start up and work with a new demo locally as possible, so if that could happen (and if `npm run demo:create` still works to create and scaffold a new demo) that'd be ideal. Would definitely love to take a look at a PR for this, thanks!

**Comment by alvarosabu** [comment]
Yes, you can start it locally, I will create a branch so you can take a look ;)

**Comment by SaFrMo** [comment]
(wontfix, new version - thanks though!)
