### ISSUE TITLE
Replace rollup build for Vite lib mode

### ISSUE THREAD

**Issue by alvarosabu** [breakfast-studio/lunchboxjs#40]
Vitejs have a lib mode for build https://vitejs.dev/guide/build.html#library-mode that uses rollup underhood.

```
//vite.config.ts
export default defineConfig({
    plugins: [vue(), glsl(), vueJsx()],
    build: {
         lib: {
           entry: resolve(__dirname, 'src/index.ts'),
            name: 'lunchboxjs',
            fileName: 'tres',
         },
    },
})
```

As for demos, check #39

**Comment by SaFrMo** [comment]
Good catch, thanks! Marking this as lower-priority for now since the dev/build process is working atm, but this is definitely a good candidate for a future fix.

**Comment by SaFrMo** [comment]
(wontfix, new version - thanks though!)
