### ISSUE TITLE
Is lodash really needed?

### ISSUE THREAD

**Issue by alvarosabu** [breakfast-studio/lunchboxjs#41]
Something that struck me a little bit when installing was the need to install `lodash` as a peer dependency. 

Since is used only on the `updateObjectPorp.ts` (The rest is used on development scripts and build scripts so could be installed as a dev dependency) I think we could replace some for local utils. wydt?.

**Comment by SaFrMo** [comment]
This absolutely makes sense - including lodash was one of those "it works for the alpha and I'll get around to fixing it later" decisions, so replacing it with local utils would be excellent! I can work on that by sometime next week unless you make a PR before then @alvarosabu , either way is good on my end.

**Comment by SaFrMo** [comment]
Fixed in #42 and released on NPM. Feel free to reopen if there are any problems - thanks!

**Comment by alvarosabu** [comment]
Nice job @SaFrMo
