### ISSUE TITLE
Failed to resolve import "../../extras/Gltf.vue" from "demo/gltf/App.vue". Does the file exist?

### ISSUE THREAD

**Issue by bperel** [breakfast-studio/lunchboxjs#49]
It looks like recently the `extras` folder disappeared, making Gltf and OrbitControlsWrapper not importable.
As a result, the Gltf demo doesn't work anymore.

**Comment by SaFrMo** [comment]
Good find, thanks for flagging! I pushed and published a fix for that and a few other demos that were broken in the move to the monorepo. Closing as complete, but please do reopen if you see any other issues like this!
