### ISSUE TITLE
Failing to get basic example running

### ISSUE THREAD

**Issue by Noxdor** [breakfast-studio/lunchboxjs#50]
I am new to lunchboxjs, just tried to get a basic example running. Unfortunately I am struggling. I did get the setup working and I can set the background color on the `lunchbox` element and see a change after refreshing the page. I also get warnings when I missspell a component name, like `BoxGeometry` instead of `boxGeometry`. Unfortunately I can't see either of the two meshes I am trying to display. Can anyone see and tell me if I am doing something wrong or what could be the issue?

main.ts:
```ts
import { createApp } from "vue"
import { lunchbox } from "lunchboxjs"
import App from "./App.vue"

createApp(App).use(lunchbox).mount("#app")
```

App.vue:
```vue
<template>
  <div>
    <h1>Lunchbox example app</h1>
    <lunchbox :root="LunchboxApp" />
  </div>
</template>

<script lang="ts" setup>
import LunchboxApp from "./lunchbox/LunchboxApp.vue"
</script>

<style scoped>
...
```

LunchboxApp.vue:
```vue
<template>
  <lunchbox background="black">
    <mesh>
      <boxGeometry />
      <meshBasicMaterial :args="[1, 2, 1]" color="green" />
    </mesh>
    <mesh>
      <torusKnotGeometry />
      <meshBasicMaterial color="white" />
    </mesh>
  </lunchbox>
</template>

<script lang="ts" setup>
import {} from "vue"

// types

// components

// composables & helpers

// stores
</script>

<style lang="scss" scoped></style>
```

**Comment by thursdaymulberry** [comment]
@Noxdor thanks for your patience, just starting back up again after the holidays! Can you try moving either the camera or the mesh? Right now it looks like both are at the same point (0, 0, 0) - instead of:

```html
<lunchbox background="black">
```

can you try:

```html
<lunchbox background="black" :cameraPosition="[0, 0, 5]">
```

and let me know if it works? Thanks!

**Comment by SaFrMo** [comment]
@Noxdor thanks for your patience, just starting back up again after the holidays! Can you try moving either the camera or the mesh? Right now it looks like both are at the same point (0, 0, 0) - instead of:

```html
<lunchbox background="black">
```

can you try:

```html
<lunchbox background="black" :cameraPosition="[0, 0, 5]">
```

and let me know if it works? Thanks!

**Comment by Noxdor** [comment]
@SaFrMo Don't worry about it, happy new year! (I know, it's late 😂) This was actually exactly the program, my bad for following a tutorial blindly :D I guess it's a good idea to keep the threejs docs open while learning lunchboxjs. Thank you for your quick and easy help!
